# Be sure to restart your server when you modify this file.

# Define an application-wide content security policy.
# See the Securing Rails Applications Guide for more information:
# https://guides.rubyonrails.org/security.html#content-security-policy-header

Rails.application.configure do
  # Nonce inline scripts generated by Rails helpers (e.g., importmap).
  config.content_security_policy_nonce_generator = ->(_request) { SecureRandom.base64(16) }
  config.content_security_policy_nonce_directives = %w(script-src)

  config.content_security_policy do |policy|
    policy.default_src :self, :https
    policy.font_src    :self, :https, :data
    policy.img_src     :self, :https, :data
    policy.object_src  :none
    policy.script_src  :self, :https
    # Turbo applies inline styles; allow inline styles to avoid CSP violations.
    policy.style_src   :self, :https, :unsafe_inline
  end

  # Enforce CSP without report-only logging noise.
  config.content_security_policy_report_only = false
end
