about:
  link1: https://www.test.com
  link2: https://www.test.com
  link3: https://www.test.com

  paragraph1: paragraph1 available now in the about_info.yml file
  paragraph2: paragraph2 available now in the about_info.yml file