budget: "💸"
career: "💼"
chores: "🧹"
cleaning: "🧼"
coding: "💻"
cooking: "🍳"
diet: "🥗"
education: "📚"
entertainment: "🎮"
family: "👨‍👩‍👧‍👦"
fabrication: "⚙"
finance: "💰"
groceries: "🛒"
health: "🧠"
hobbies: "🎸"
meeeting: "📅"
networking: "🤝"
outdoors: "🌲"
paddleboarding: "🏄‍♂️"
pets: "🐾"
relationships: "❤️"
running: "🏃‍♂️"
shop: "🔩"
shopping: "🛍️"
sleep: "😴"
social: "🥂"
travel: "✈"
workout: "🏋️"

edit: "✏️"
back: "⬅️"
task: "✅"
calendar: "📆"
goal: "🎯"
dashboard: "📊"