finance: "💰"
health: "🧠"
workout: "🏋️"
chores: "🧹"
groceries: "🛒"
education: "📚"
meeeting: "📅"
coding: "💻"
shop: "🔩"
fabrication: "⚙"
travel: "✈"
family: "👨‍👩‍👧‍👦"
entertainment: "🎮"
social: "🥂"

edit: "✏️"
back: "⬅️"
task: "✅"
calendar: "📆"
goal: "🎯"